apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mlha/kubernetes_angular:v1
---

apiVersion: v1
kind: Service
metadata:
  name: frontend

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: frontend

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort